const elements=[['H','Wasserstoff',[1]],['He','Helium',[2]],['Li','Lithium',[2,1]],['Be','Beryllium',[2,2]],['B','Bor',[2,3]],['C','Kohlenstoff',[2,4]],['N','Stickstoff',[2,5]],['O','Sauerstoff',[2,6]],['F','Fluor',[2,7]],['Ne','Neon',[2,8]],['Na','Natrium',[2,8,1]],['Mg','Magnesium',[2,8,2]],['Al','Aluminium',[2,8,3]],['Si','Silicium',[2,8,4]],['P','Phosphor',[2,8,5]],['S','Schwefel',[2,8,6]],['Cl','Chlor',[2,8,7]],['Ar','Argon',[2,8,8]],['K','Kalium',[2,8,8,1]],['Ca','Calcium',[2,8,8,2]]];
let index=10,delta=0;
const $=id=>document.getElementById(id);
function model(i,d){const [symbol,name,base]=elements[i],shells=[...base],last=shells.length-1,capacity=last===0?2:8; shells[last]+=d;return {symbol,name,shells,z:i+1,e:i+1+d,min:-base[last],max:capacity-base[last],charge:-d};}
function chargeText(q){return q===0?'':`${Math.abs(q)===1?'':Math.abs(q)}${q>0?'+':'−'}`;}
function render(){const m=model(index,delta);$('name').textContent=m.name;$('kind').textContent=m.charge===0?'Atom':'Ion';$('number').textContent=`ORDNUNGSZAHL ${m.z}`;$('symbol').innerHTML=`${m.symbol}<sup>${chargeText(m.charge)}</sup>`;$('protons').textContent=m.z;$('electrons').textContent=m.e;$('charge').textContent=m.charge===0?'Elektrisch neutral':`${Math.abs(m.charge)}-fach ${m.charge>0?'positiv':'negativ'} geladen`;$('element').value=index;$('prev').disabled=index===0;$('next').disabled=index===19;$('remove').disabled=delta===m.min;$('add').disabled=delta===m.max;$('reset').disabled=delta===0;
const outer=m.shells.at(-1),cap=m.shells.length===1?2:8;$('hint').textContent=outer===0?'Äußerste Schale leer: Es können keine weiteren Elektronen abgegeben werden.':outer===cap?'Äußerste Schale voll: Es können keine weiteren Elektronen aufgenommen werden.':`${outer} von ${cap} Elektronen auf der äußersten Schale`;
let svg=`<defs><radialGradient id="red" cx="30%" cy="25%"><stop stop-color="#ff9a84"/><stop offset=".55" stop-color="#ec4938"/><stop offset="1" stop-color="#af241e"/></radialGradient><radialGradient id="white" cx="30%" cy="25%"><stop stop-color="#fff"/><stop offset=".6" stop-color="#e4ebef"/><stop offset="1" stop-color="#aabac4"/></radialGradient></defs>`;
m.shells.forEach((n,k)=>{const r=92+k*51;svg+=`<circle cx="320" cy="280" r="${r}" fill="none" stroke="#b8cbd7" stroke-width="2" ${n===0?'stroke-dasharray="6 7"':''}/><text x="${320+r+9}" y="285" fill="#6a8394" font-size="15">${['K','L','M','N'][k]}</text>`;for(let j=0;j<n;j++){const a=-Math.PI/2+j*2*Math.PI/n;svg+=`<circle cx="${320+r*Math.cos(a)}" cy="${280+r*Math.sin(a)}" r="9" fill="#1588a2" stroke="white" stroke-width="2"/>`;}});
const balls=[[0,-38],[-28,-29],[29,-27],[-42,-6],[43,0],[-30,27],[28,31],[0,42],[-11,-13],[18,-4],[-13,18],[9,18]];balls.forEach(([x,y],k)=>{svg+=`<circle cx="${320+x}" cy="${280+y}" r="25" fill="url(#${k%3===0?'white':'red'})" stroke="${k%3===0?'#aabac4':'#b8372b'}" stroke-width="1"/>`;});svg+=`<rect x="279" y="258" width="82" height="44" rx="22" fill="#721e1a" fill-opacity=".88"/><text x="320" y="288" text-anchor="middle" font-family="system-ui,sans-serif" font-size="28" font-weight="750" fill="white">${m.z}+</text>`;$('atom').innerHTML=svg;$('atom').setAttribute('aria-label',`${m.name}, ${m.z} Protonen, ${m.e} Elektronen. Schalenbesetzung: ${m.shells.join(', ')}. Der Kern ist schematisch dargestellt.`);
}
$('element').innerHTML=elements.map((e,i)=>`<option value="${i}">${i+1} · ${e[1]} (${e[0]})</option>`).join('');
function select(i){index=i;delta=0;render();}
$('start').onclick=()=>{$('menu').hidden=true;$('app').hidden=false;$('back').focus();};$('back').onclick=()=>{$('app').hidden=true;$('menu').hidden=false;$('start').focus();};$('prev').onclick=()=>select(Math.max(0,index-1));$('next').onclick=()=>select(Math.min(19,index+1));$('element').onchange=e=>select(Number(e.target.value));$('reset').onclick=()=>{delta=0;render();};$('add').onclick=()=>{if(delta<model(index,delta).max)delta++;render();};$('remove').onclick=()=>{if(delta>model(index,delta).min)delta--;render();};render();
